-- MySQL Script generated by MySQL Workbench
-- Friday 13 November 2020 03:35:08 PM
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema feedback
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema feedback
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `feedback` ;
USE `feedback` ;

-- -----------------------------------------------------
-- Table `feedback`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `feedback`.`category` ;

CREATE TABLE IF NOT EXISTS `feedback`.`category` (
  `catId` INT NOT NULL AUTO_INCREMENT,
  `catDesc` VARCHAR(20) NOT NULL,
  `catLastUpdatedBy` VARCHAR(45) NULL,
  `catLastUpdatedTime` DATE NULL,
  PRIMARY KEY (`catId`, `catDesc`),
  INDEX `index2` (`catDesc` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `feedback`.`subcategory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `feedback`.`subcategory` ;

CREATE TABLE IF NOT EXISTS `feedback`.`subcategory` (
  `subcatId` INT NOT NULL AUTO_INCREMENT,
  `catId` INT NOT NULL,
  `subcatDesc` VARCHAR(20) NOT NULL,
  `subcatMTTR` INT NULL,
  `subcatType` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`subcatId`, `catId`),
  INDEX `fk_subcategory_1_idx` (`catId` ASC) ,
  CONSTRAINT `fk_subcategory_1`
    FOREIGN KEY (`catId`)
    REFERENCES `feedback`.`category` (`catId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `feedback`.`complaint`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `feedback`.`complaint` ;

CREATE TABLE IF NOT EXISTS `feedback`.`complaint` (
  `compId` INT NOT NULL AUTO_INCREMENT,
  `catId` INT NOT NULL,
  `subcatId` INT NOT NULL,
  `compDesc` VARCHAR(100) NOT NULL,
  `compStatus` INT NOT NULL,
  `compEmail` VARCHAR(45) NOT NULL,
  `compToEmail` VARCHAR(45) NULL,
  PRIMARY KEY (`compId`, `catId`, `subcatId`),
  INDEX `fk_complaint_1_idx` (`catId` ASC, `subcatId` ASC) ,
  CONSTRAINT `fk_complaint_1`
    FOREIGN KEY (`catId` , `subcatId`)
    REFERENCES `feedback`.`subcategory` (`catId` , `subcatId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `feedback`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `feedback`.`role` ;

CREATE TABLE IF NOT EXISTS `feedback`.`role` (
  `roleId` INT NOT NULL AUTO_INCREMENT,
  `roleDesc` VARCHAR(45) NULL,
  PRIMARY KEY (`roleId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `feedback`.`feedbacks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `feedback`.`feedbacks` ;

CREATE TABLE IF NOT EXISTS `feedback`.`feedbacks` (
  `fbId` INT NOT NULL AUTO_INCREMENT,
  `catId` INT NULL,
  `fbSubj` VARCHAR(45) NULL,
  `fbDesc` VARCHAR(200) NULL,
  `fbEmail` VARCHAR(45) NULL,
  PRIMARY KEY (`fbId`),
  INDEX `fk_feedbacks_1_idx` (`catId` ASC) ,
  CONSTRAINT `fk_feedbacks_1`
    FOREIGN KEY (`catId`)
    REFERENCES `feedback`.`category` (`catId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `feedback`.`fbupvote`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `feedback`.`fbupvote` ;

CREATE TABLE IF NOT EXISTS `feedback`.`fbupvote` (
  `upId` INT NOT NULL AUTO_INCREMENT,
  `fbId` INT NULL,
  `upvoteEmail` VARCHAR(45) NULL,
  PRIMARY KEY (`upId`),
  INDEX `fk_fbupvote_1_idx` (`fbId` ASC) ,
  CONSTRAINT `fk_fbupvote_1`
    FOREIGN KEY (`fbId`)
    REFERENCES `feedback`.`feedbacks` (`fbId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `feedback`.`fbdownvote`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `feedback`.`fbdownvote` ;

CREATE TABLE IF NOT EXISTS `feedback`.`fbdownvote` (
  `downId` INT NOT NULL AUTO_INCREMENT,
  `fbId` INT NULL,
  `downvoteEmail` VARCHAR(45) NULL,
  PRIMARY KEY (`downId`),
  INDEX `fk_fbdownvote_1_idx` (`fbId` ASC) ,
  CONSTRAINT `fk_fbdownvote_1`
    FOREIGN KEY (`fbId`)
    REFERENCES `feedback`.`feedbacks` (`fbId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `feedback`.`categorysupervisor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `feedback`.`categorysupervisor` ;

CREATE TABLE IF NOT EXISTS `feedback`.`categorysupervisor` (
  `catRoleId` INT NOT NULL AUTO_INCREMENT,
  `catId` INT NOT NULL,
  `catRoleEmail` VARCHAR(45) NULL,
  INDEX `fk_categorysupervisor_1_idx` (`catId` ASC) ,
  PRIMARY KEY (`catRoleId`, `catId`),
  CONSTRAINT `fk_categorysupervisor_1`
    FOREIGN KEY (`catId`)
    REFERENCES `feedback`.`category` (`catId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
