-- MySQL Script generated by MySQL Workbench
-- Tuesday 08 September 2020 06:33:22 PM IST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema feedbacksystem
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema feedbacksystem
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `feedbacksystem` ;
USE `feedbacksystem` ;

-- -----------------------------------------------------
-- Table `feedbacksystem`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `feedbacksystem`.`category` ;

CREATE TABLE IF NOT EXISTS `feedbacksystem`.`category` (
  `id` INT NOT NULL,
  `categoryname` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`, `categoryname`),
  INDEX `index2` (`categoryname` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `feedbacksystem`.`subcategory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `feedbacksystem`.`subcategory` ;

CREATE TABLE IF NOT EXISTS `feedbacksystem`.`subcategory` (
  `id` INT NOT NULL,
  `categoryname` VARCHAR(20) NOT NULL,
  `subcategoryname` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`, `categoryname`, `subcategoryname`),
  INDEX `fk_subcategory_1_idx` (`categoryname` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `feedbacksystem`.`complaint`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `feedbacksystem`.`complaint` ;

CREATE TABLE IF NOT EXISTS `feedbacksystem`.`complaint` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `categoryname` VARCHAR(20) NOT NULL,
  `subcategoryname` VARCHAR(20) NOT NULL,
  `description` VARCHAR(100) NULL,
  PRIMARY KEY (`id`, `categoryname`, `subcategoryname`),
  INDEX `fk_complaint_1_idx` (`categoryname` ASC, `subcategoryname` ASC) )
ENGINE = InnoDB;

ALTER TABLE complaint AUTO_INCREMENT=10000;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
