-- MySQL Script generated by MySQL Workbench
-- Friday 11 September 2020 12:38:21 PM IST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema feedback
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema feedback
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `feedback` ;
USE `feedback` ;

-- -----------------------------------------------------
-- Table `feedback`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `feedback`.`category` ;

CREATE TABLE IF NOT EXISTS `feedback`.`category` (
  `catId` INT NOT NULL,
  `catDesc` VARCHAR(20) NOT NULL,
  `catLastUpdatedBy` VARCHAR(45) NULL,
  `catLastUpdatedTime` DATE NULL,
  PRIMARY KEY (`catId`, `catDesc`),
  INDEX `index2` (`catDesc` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `feedback`.`subcategory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `feedback`.`subcategory` ;

CREATE TABLE IF NOT EXISTS `feedback`.`subcategory` (
  `subcatId` INT NOT NULL,
  `catId` INT NOT NULL,
  `subcatDesc` VARCHAR(20) NOT NULL,
  `subcatMTTR` INT NULL,
  PRIMARY KEY (`subcatId`, `catId`),
  INDEX `fk_subcategory_1_idx` (`catId` ASC) ,
  CONSTRAINT `fk_subcategory_1`
    FOREIGN KEY (`catId`)
    REFERENCES `feedback`.`category` (`catId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `feedback`.`complaint`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `feedback`.`complaint` ;

CREATE TABLE IF NOT EXISTS `feedback`.`complaint` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `catId` INT NOT NULL,
  `subcatId` INT NOT NULL,
  `compDesc` VARCHAR(100) NOT NULL,
  `compStatus` INT NOT NULL,
  PRIMARY KEY (`id`, `catId`, `subcatId`),
  INDEX `fk_complaint_1_idx` (`catId` ASC, `subcatId` ASC) ,
  CONSTRAINT `fk_complaint_1`
    FOREIGN KEY (`catId` , `subcatId`)
    REFERENCES `feedback`.`subcategory` (`catId` , `subcatId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `feedback`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `feedback`.`role` ;

CREATE TABLE IF NOT EXISTS `feedback`.`role` (
  `roleId` INT NOT NULL,
  `roleDesc` VARCHAR(45) NULL,
  PRIMARY KEY (`roleId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `feedback`.`feedback`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `feedback`.`feedback` ;

CREATE TABLE IF NOT EXISTS `feedback`.`feedback` (
)
ENGINE = InnoDB;

ALTER TABLE complaint AUTO_INCREMENT=1000;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
